#include <toh.hpp>
#include <vector>
#include <sstream>
#include <iomanip>

toh::Options::Options() :
	null(false),
	variable("buffer")
{
}

std::string toh::convert(const char* buffer, size_t length, const toh::Options& options)
{
	std::ostringstream output;
	output << "// This file is autogenerated!\n";
	output << "const unsigned int " << options.variable << "_len = " << (length + (options.null ? 1 : 0)) << ";\n";
	output << "const unsigned char " << options.variable << "[] = {";
	for (size_t i = 0; i < length + (options.null ? 1 : 0); ++i) 
	{
		if (i != 0) output << ",";
		if (i % 20 == 0) output << "\n  ";
		if (i == length) output << "0x00";
		else output << "0x" << std::setw(2) << std::setfill('0') << std::hex << (unsigned int)(unsigned char)buffer[i];
	}
	output << "\n};";
	return output.str();
}
